2014-04-04 12:44:47,598 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-04-04 12:44:48,863 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-04-04 12:44:49,145 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-04-04 12:44:49,168 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-04-04 12:44:49,196 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-04-04 12:44:49,196 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-04-04 12:44:49,298 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-04-04 12:44:52,987 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/share/software-center/softwarecenter/utils.py', 271, 'get_title_from_html')'
2014-04-04 12:44:52,987 - root - WARNING - failed to parse: '<div style="background-color: #161513; width:1680px; height:200px;">
Â <div style="background: url('/site_media/exhibits/2013/09/AAMFP_Leaderboard_700x200_1.jpg') top left no-repeat; width:700px; height:200px;"></div>
</div>' ('ascii' codec can't encode character u'\xa0' in position 70: ordinal not in range(128))
2014-04-04 12:44:53,003 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'amnesia-amfp'' not available
2014-04-04 12:44:59,985 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-04-04 12:49:12,155 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-04-04 12:49:23,064 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-06-16 17:09:30,322 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-06-16 17:09:31,614 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-06-16 17:09:32,075 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-06-16 17:09:32,102 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-06-16 17:09:32,124 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-06-16 17:09:32,124 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-06-16 17:09:32,244 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-06-16 17:09:36,223 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-06-16 17:09:40,059 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-06-16 17:09:40,059 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-06-16 17:09:44,917 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-06-16 17:11:43,699 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-06-16 17:11:54,239 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-07-04 18:50:30,593 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-07-04 18:50:31,297 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-07-04 18:50:31,796 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-07-04 18:50:31,818 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-07-04 18:50:31,840 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-07-04 18:50:31,840 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-07-04 18:50:31,989 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-07-04 18:50:34,788 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-07-04 18:50:34,822 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-07-04 18:50:34,845 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-07-04 18:50:42,481 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-07-04 18:53:09,492 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-07-04 18:53:09,947 - softwarecenter.backend.zeitgeist_logger - WARNING - Invalid desktop file provided, impossible to log event
2014-07-04 18:53:19,864 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-08-22 14:23:34,121 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-08-22 14:23:35,730 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-08-22 14:23:36,264 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-08-22 14:23:36,283 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-08-22 14:23:36,305 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-08-22 14:23:36,305 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-08-22 14:23:36,525 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-08-22 14:23:40,487 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-08-22 14:23:40,513 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-08-22 14:23:40,851 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-08-22 14:23:49,467 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-08-22 14:25:50,267 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-08-22 14:26:00,583 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-08-22 14:46:38,203 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-08-22 14:46:38,741 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-08-22 14:46:38,743 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-08-22 14:46:38,746 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-08-22 14:46:38,746 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-08-22 14:46:38,860 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-08-22 14:46:40,363 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-08-22 14:46:40,363 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-08-22 14:46:41,156 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-08-22 14:46:49,085 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-09-26 15:23:27,213 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-09-26 15:23:27,812 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-09-26 15:23:28,297 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-09-26 15:23:28,299 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-09-26 15:23:28,349 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-09-26 15:23:28,349 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-09-26 15:23:28,444 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-26 15:23:31,664 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-09-26 15:23:31,687 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-09-26 15:23:31,730 - softwarecenter.ui.gtk3.views.lobbyview - WARNING - skipping exhibit for: 'u'leadwerks\r\nleadwerks-indie'' not available
2014-09-26 15:23:33,414 - softwarecenter.db.pkginfo_impl.aptcache - ERROR - simulate failed
None
2014-09-26 15:23:34,968 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "mysql-apt-config"}']'
2014-09-26 15:23:34,969 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from sumac.canonical.com', 'transfer-encoding': 'chunked', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 06:23:34 GMT', 'content-type': 'text/html; charset=utf-8'}
'
2014-09-26 15:23:34,969 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from sumac.canonical.com', 'transfer-encoding': 'chunked', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 06:23:34 GMT', 'content-type': 'text/html; charset=utf-8'}

2014-09-26 15:23:34,969 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'via': '1.1 sumac.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from sumac.canonical.com', 'transfer-encoding': 'chunked', 'x-cache-lookup': 'HIT from sumac.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 06:23:34 GMT', 'content-type': 'text/html; charset=utf-8'}

2014-09-26 15:23:40,395 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-09-26 15:24:02,758 - softwarecenter.backend - WARNING - _on_trans_error: 'NotAuthorizedError(u"('system-bus-name', {'name':  ':1.115'}): org.debian.apt.install-file",)' '<AptTransaction object at 0x7f9cd41e7230 (aptdaemon+client+AptTransaction at 0x1bca460)>' 'mysql-apt-config'
2014-09-26 15:24:02,761 - softwarecenter.backend - ERROR - error in _on_trans_finished 'ã¨ã©ã¼: ãã®ã¢ã¯ã·ã§ã³ãå®è¡ããæ¨©éãããã¾ãã
ãã®ã¢ã¯ã·ã§ã³ãå®è¡ããã®ã«å¿è¦ãªç¹æ¨©ãããã¾ããã

org.freedesktop.PolicyKit.Error.NotAuthorized: ('system-bus-name', {'name': ':1.115'}): org.debian.apt.install-file'
2014-09-26 15:24:03,981 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-26 15:30:29,688 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-26 15:30:32,770 - softwarecenter.utils - WARNING - Could not determine the installed desktop file path for app-install desktop file: 'None'
2014-09-26 15:30:32,770 - softwarecenter.backend.zeitgeist_logger - WARNING - Invalid desktop file provided, impossible to log event
2014-09-26 16:03:06,521 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-09-26 16:03:07,049 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-09-26 16:03:07,051 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-09-26 16:03:07,054 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-09-26 16:03:07,054 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-09-26 16:03:07,095 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-26 16:03:08,442 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-09-26 16:03:08,442 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-09-26 16:03:12,842 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "mysql-apt-config"}']'
2014-09-26 16:03:12,842 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from papeda.canonical.com', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 07:03:12 GMT', 'content-type': 'text/html; charset=utf-8'}
'
2014-09-26 16:03:12,843 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from papeda.canonical.com', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 07:03:12 GMT', 'content-type': 'text/html; charset=utf-8'}

2014-09-26 16:03:12,843 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from papeda.canonical.com', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 07:03:12 GMT', 'content-type': 'text/html; charset=utf-8'}

2014-09-26 16:03:20,206 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-09-26 16:21:04,434 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-09-26 16:21:04,953 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-09-26 16:21:04,955 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-09-26 16:21:04,959 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-09-26 16:21:04,958 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-09-26 16:21:05,001 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-09-26 16:21:05,282 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-09-26 16:21:05,282 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-09-26 16:21:09,323 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "mysql-apt-config"}']'
2014-09-26 16:21:09,323 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '93', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 07:19:36 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}
'
2014-09-26 16:21:09,323 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '93', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 07:19:36 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}

2014-09-26 16:21:09,324 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '93', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Fri, 26 Sep 2014 07:19:36 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}

2014-09-26 16:21:15,391 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-10-02 17:27:00,878 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-10-02 17:27:02,362 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2014-10-02 17:27:03,172 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-10-02 17:27:03,192 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-10-02 17:27:03,214 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-10-02 17:27:03,214 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-10-02 17:27:03,311 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-10-02 17:27:06,385 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-10-02 17:27:06,402 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-10-02 17:27:09,229 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "mysql-apt-config"}']'
2014-10-02 17:27:09,230 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from papeda.canonical.com', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Thu, 02 Oct 2014 08:27:09 GMT', 'content-type': 'text/html; charset=utf-8'}
'
2014-10-02 17:27:09,230 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from papeda.canonical.com', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Thu, 02 Oct 2014 08:27:09 GMT', 'content-type': 'text/html; charset=utf-8'}

2014-10-02 17:27:09,230 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'MISS from papeda.canonical.com', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Thu, 02 Oct 2014 08:27:09 GMT', 'content-type': 'text/html; charset=utf-8'}

2014-10-02 17:27:14,360 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-10-02 17:29:36,479 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2014-10-02 17:29:36,815 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2014-10-02 17:29:36,817 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2014-10-02 17:29:36,820 - softwarecenter.fixme - WARNING - logs to the root logger: '('/usr/lib/python2.7/dist-packages/gi/importer.py', 51, 'find_module')'
2014-10-02 17:29:36,820 - root - ERROR - Could not find any typelib for LaunchpadIntegration
2014-10-02 17:29:36,969 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2014-10-02 17:29:37,696 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2014-10-02 17:29:37,696 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, '\xe7\x84\xa1\xe5\x8a\xb9\xe3\x81\xaa\xe5\xbc\x95\xe6\x95\xb0\xe3\x81\xa7\xe3\x81\x99 -- BDB0054 illegal flag combination specified to DB_ENV->open')
2014-10-02 17:29:40,628 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterRecommenderAPI', 'recommend_app', '{"pkgname": "mysql-apt-config"}']'
2014-10-02 17:29:40,628 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '151', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Thu, 02 Oct 2014 08:27:09 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}
'
2014-10-02 17:29:40,629 - softwarecenter.db.categories - WARNING - Error while accessing the recommender service: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '151', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Thu, 02 Oct 2014 08:27:09 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}

2014-10-02 17:29:40,629 - softwarecenter.ui.gtk3.widgets.recommendations - WARNING - Error while accessing the recommender agent: WARNING:__main__:404: {'status': '404', 'content-length': '65', 'via': '1.1 papeda.canonical.com:3128 (squid/2.7.STABLE7)', 'x-cache': 'HIT from papeda.canonical.com', 'age': '151', 'strict-transport-security': 'max-age=2592000', 'server': 'Apache/2.2.22 (Ubuntu)', 'etag': '"3492afba21753d18bba6a7908bb29243"', 'cache-control': 'max-age=300', 'date': 'Thu, 02 Oct 2014 08:27:09 GMT', 'content-type': 'text/html; charset=utf-8', 'x-cache-lookup': 'HIT from papeda.canonical.com:3128'}

2014-10-02 17:29:42,752 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2014-10-02 17:30:20,788 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
